/*
 * Auto-generated by: https://github.com/pmndrs/gltfjsx
 * Author: tzeshi (https://sketchfab.com/timvizesi)
 * License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
 * Source: https://sketchfab.com/3d-models/apple-macintosh-608e0f6ce5e9487eb859f48248e1fac4
 * Title: Apple Macintosh
 *
 * Additional Modifications:
 * Author: Evgenii Gulev
 * Date/Time: 2024-06-06
 */

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import macintoshScene from "../assets/3d/macintosh.glb";

const Macintosh = ({ ...props }) => {
  // Create a ref to the Macintosh group
  const macRef = useRef();
  // Load GLTF model
  const { nodes, materials } = useGLTF(macintoshScene);

  return (
    <group ref={macRef} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        {/* Main body of the Macintosh */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials["02___Default"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.Background}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.dark_beige}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.dark_grey}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.darker_beige}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.darker_beige}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.darkest_beige}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.darkest_beige}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.light_beige}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials.lighter_beige}
        />
      </group>
    </group>
  );
};

export default Macintosh;
